name = "lock-in-landing-page"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = ".vercel/output/static" 